apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbf-data
  namespace: dbf
  labels:
    app: distributed-bloom-filter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
