// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/dbf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddRequest is the request message for the Add RPC.
type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The item to add to the Bloom filter.
	Item          []byte `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

// AddResponse is the response message for the Add RPC.
type AddResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates whether the operation succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error contains an error message if the operation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RemoveRequest is the request message for the Remove RPC.
type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The item to remove from the Bloom filter.
	Item          []byte `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

// RemoveResponse is the response message for the Remove RPC.
type RemoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates whether the operation succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error contains an error message if the operation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ContainsRequest is the request message for the Contains RPC.
type ContainsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The item to check in the Bloom filter.
	Item          []byte `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsRequest) Reset() {
	*x = ContainsRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsRequest) ProtoMessage() {}

func (x *ContainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsRequest.ProtoReflect.Descriptor instead.
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{4}
}

func (x *ContainsRequest) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

// ContainsResponse is the response message for the Contains RPC.
type ContainsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exists indicates whether the item is in the Bloom filter.
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// Error contains an error message if the operation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsResponse) Reset() {
	*x = ContainsResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsResponse) ProtoMessage() {}

func (x *ContainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsResponse.ProtoReflect.Descriptor instead.
func (*ContainsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{5}
}

func (x *ContainsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ContainsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchAddRequest is the request message for the BatchAdd RPC.
type BatchAddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The items to add to the Bloom filter.
	Items         [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddRequest) Reset() {
	*x = BatchAddRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddRequest) ProtoMessage() {}

func (x *BatchAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddRequest.ProtoReflect.Descriptor instead.
func (*BatchAddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{6}
}

func (x *BatchAddRequest) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// BatchAddResponse is the response message for the BatchAdd RPC.
type BatchAddResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SuccessCount is the number of items successfully added.
	SuccessCount int32 `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// FailureCount is the number of items that failed to add.
	FailureCount int32 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// Errors contains error messages for failed items (indexed by item position).
	Errors        []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddResponse) Reset() {
	*x = BatchAddResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddResponse) ProtoMessage() {}

func (x *BatchAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddResponse.ProtoReflect.Descriptor instead.
func (*BatchAddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{7}
}

func (x *BatchAddResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchAddResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchAddResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// BatchContainsRequest is the request message for the BatchContains RPC.
type BatchContainsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The items to check in the Bloom filter.
	Items         [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchContainsRequest) Reset() {
	*x = BatchContainsRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchContainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchContainsRequest) ProtoMessage() {}

func (x *BatchContainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchContainsRequest.ProtoReflect.Descriptor instead.
func (*BatchContainsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{8}
}

func (x *BatchContainsRequest) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// BatchContainsResponse is the response message for the BatchContains RPC.
type BatchContainsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results contains the existence status for each item.
	Results []bool `protobuf:"varint,1,rep,packed,name=results,proto3" json:"results,omitempty"`
	// Error contains an error message if the operation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchContainsResponse) Reset() {
	*x = BatchContainsResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchContainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchContainsResponse) ProtoMessage() {}

func (x *BatchContainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchContainsResponse.ProtoReflect.Descriptor instead.
func (*BatchContainsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{9}
}

func (x *BatchContainsResponse) GetResults() []bool {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchContainsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetStatsRequest is the request message for the GetStats RPC.
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_dbf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{10}
}

// GetStatsResponse is the response message for the GetStats RPC.
type GetStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeID is the unique identifier of this node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// IsLeader indicates whether this node is the Raft leader.
	IsLeader bool `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// RaftState is the current Raft state (e.g., "Leader", "Follower", "Candidate").
	RaftState string `protobuf:"bytes,3,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	// Leader is the address of the current Raft leader.
	Leader string `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	// BloomSize is the size of the Bloom filter in bits.
	BloomSize int64 `protobuf:"varint,5,opt,name=bloom_size,json=bloomSize,proto3" json:"bloom_size,omitempty"`
	// BloomK is the number of hash functions.
	BloomK int32 `protobuf:"varint,6,opt,name=bloom_k,json=bloomK,proto3" json:"bloom_k,omitempty"`
	// BloomCount is the approximate number of items in the filter.
	BloomCount int64 `protobuf:"varint,7,opt,name=bloom_count,json=bloomCount,proto3" json:"bloom_count,omitempty"`
	// RaftPort is the port used for Raft consensus.
	RaftPort int32 `protobuf:"varint,8,opt,name=raft_port,json=raftPort,proto3" json:"raft_port,omitempty"`
	// Error contains an error message if the operation failed.
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_dbf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dbf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dbf_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetStatsResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *GetStatsResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *GetStatsResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *GetStatsResponse) GetBloomSize() int64 {
	if x != nil {
		return x.BloomSize
	}
	return 0
}

func (x *GetStatsResponse) GetBloomK() int32 {
	if x != nil {
		return x.BloomK
	}
	return 0
}

func (x *GetStatsResponse) GetBloomCount() int64 {
	if x != nil {
		return x.BloomCount
	}
	return 0
}

func (x *GetStatsResponse) GetRaftPort() int32 {
	if x != nil {
		return x.RaftPort
	}
	return 0
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_dbf_proto protoreflect.FileDescriptor

const file_api_proto_dbf_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/dbf.proto\x12\x03dbf\" \n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04item\x18\x01 \x01(\fR\x04item\"=\n" +
	"\vAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04item\x18\x01 \x01(\fR\x04item\"@\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fContainsRequest\x12\x12\n" +
	"\x04item\x18\x01 \x01(\fR\x04item\"@\n" +
	"\x10ContainsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x0fBatchAddRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"t\n" +
	"\x10BatchAddResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\",\n" +
	"\x14BatchContainsRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"G\n" +
	"\x15BatchContainsResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\bR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fGetStatsRequest\"\x8b\x02\n" +
	"\x10GetStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x03 \x01(\tR\traftState\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\tR\x06leader\x12\x1d\n" +
	"\n" +
	"bloom_size\x18\x05 \x01(\x03R\tbloomSize\x12\x17\n" +
	"\abloom_k\x18\x06 \x01(\x05R\x06bloomK\x12\x1f\n" +
	"\vbloom_count\x18\a \x01(\x03R\n" +
	"bloomCount\x12\x1b\n" +
	"\traft_port\x18\b \x01(\x05R\braftPort\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error2\xdc\x02\n" +
	"\n" +
	"DBFService\x12(\n" +
	"\x03Add\x12\x0f.dbf.AddRequest\x1a\x10.dbf.AddResponse\x121\n" +
	"\x06Remove\x12\x12.dbf.RemoveRequest\x1a\x13.dbf.RemoveResponse\x127\n" +
	"\bContains\x12\x14.dbf.ContainsRequest\x1a\x15.dbf.ContainsResponse\x127\n" +
	"\bBatchAdd\x12\x14.dbf.BatchAddRequest\x1a\x15.dbf.BatchAddResponse\x12F\n" +
	"\rBatchContains\x12\x19.dbf.BatchContainsRequest\x1a\x1a.dbf.BatchContainsResponse\x127\n" +
	"\bGetStats\x12\x14.dbf.GetStatsRequest\x1a\x15.dbf.GetStatsResponseB;Z9github.com/wangminggit/distributed-bloom-filter/api/protob\x06proto3"

var (
	file_api_proto_dbf_proto_rawDescOnce sync.Once
	file_api_proto_dbf_proto_rawDescData []byte
)

func file_api_proto_dbf_proto_rawDescGZIP() []byte {
	file_api_proto_dbf_proto_rawDescOnce.Do(func() {
		file_api_proto_dbf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dbf_proto_rawDesc), len(file_api_proto_dbf_proto_rawDesc)))
	})
	return file_api_proto_dbf_proto_rawDescData
}

var file_api_proto_dbf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_dbf_proto_goTypes = []any{
	(*AddRequest)(nil),            // 0: dbf.AddRequest
	(*AddResponse)(nil),           // 1: dbf.AddResponse
	(*RemoveRequest)(nil),         // 2: dbf.RemoveRequest
	(*RemoveResponse)(nil),        // 3: dbf.RemoveResponse
	(*ContainsRequest)(nil),       // 4: dbf.ContainsRequest
	(*ContainsResponse)(nil),      // 5: dbf.ContainsResponse
	(*BatchAddRequest)(nil),       // 6: dbf.BatchAddRequest
	(*BatchAddResponse)(nil),      // 7: dbf.BatchAddResponse
	(*BatchContainsRequest)(nil),  // 8: dbf.BatchContainsRequest
	(*BatchContainsResponse)(nil), // 9: dbf.BatchContainsResponse
	(*GetStatsRequest)(nil),       // 10: dbf.GetStatsRequest
	(*GetStatsResponse)(nil),      // 11: dbf.GetStatsResponse
}
var file_api_proto_dbf_proto_depIdxs = []int32{
	0,  // 0: dbf.DBFService.Add:input_type -> dbf.AddRequest
	2,  // 1: dbf.DBFService.Remove:input_type -> dbf.RemoveRequest
	4,  // 2: dbf.DBFService.Contains:input_type -> dbf.ContainsRequest
	6,  // 3: dbf.DBFService.BatchAdd:input_type -> dbf.BatchAddRequest
	8,  // 4: dbf.DBFService.BatchContains:input_type -> dbf.BatchContainsRequest
	10, // 5: dbf.DBFService.GetStats:input_type -> dbf.GetStatsRequest
	1,  // 6: dbf.DBFService.Add:output_type -> dbf.AddResponse
	3,  // 7: dbf.DBFService.Remove:output_type -> dbf.RemoveResponse
	5,  // 8: dbf.DBFService.Contains:output_type -> dbf.ContainsResponse
	7,  // 9: dbf.DBFService.BatchAdd:output_type -> dbf.BatchAddResponse
	9,  // 10: dbf.DBFService.BatchContains:output_type -> dbf.BatchContainsResponse
	11, // 11: dbf.DBFService.GetStats:output_type -> dbf.GetStatsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_dbf_proto_init() }
func file_api_proto_dbf_proto_init() {
	if File_api_proto_dbf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dbf_proto_rawDesc), len(file_api_proto_dbf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dbf_proto_goTypes,
		DependencyIndexes: file_api_proto_dbf_proto_depIdxs,
		MessageInfos:      file_api_proto_dbf_proto_msgTypes,
	}.Build()
	File_api_proto_dbf_proto = out.File
	file_api_proto_dbf_proto_goTypes = nil
	file_api_proto_dbf_proto_depIdxs = nil
}
