// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/dbf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBFService_Add_FullMethodName           = "/dbf.DBFService/Add"
	DBFService_Remove_FullMethodName        = "/dbf.DBFService/Remove"
	DBFService_Contains_FullMethodName      = "/dbf.DBFService/Contains"
	DBFService_BatchAdd_FullMethodName      = "/dbf.DBFService/BatchAdd"
	DBFService_BatchContains_FullMethodName = "/dbf.DBFService/BatchContains"
	DBFService_GetStats_FullMethodName      = "/dbf.DBFService/GetStats"
)

// DBFServiceClient is the client API for DBFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DBFService provides the gRPC API for the Distributed Bloom Filter.
type DBFServiceClient interface {
	// Add adds an item to the Bloom filter.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Remove removes an item from the Bloom filter.
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// Contains checks if an item exists in the Bloom filter.
	Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error)
	// BatchAdd adds multiple items to the Bloom filter.
	BatchAdd(ctx context.Context, in *BatchAddRequest, opts ...grpc.CallOption) (*BatchAddResponse, error)
	// BatchContains checks if multiple items exist in the Bloom filter.
	BatchContains(ctx context.Context, in *BatchContainsRequest, opts ...grpc.CallOption) (*BatchContainsResponse, error)
	// GetStats returns statistics about the Bloom filter and node.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type dBFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDBFServiceClient(cc grpc.ClientConnInterface) DBFServiceClient {
	return &dBFServiceClient{cc}
}

func (c *dBFServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, DBFService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBFServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, DBFService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBFServiceClient) Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainsResponse)
	err := c.cc.Invoke(ctx, DBFService_Contains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBFServiceClient) BatchAdd(ctx context.Context, in *BatchAddRequest, opts ...grpc.CallOption) (*BatchAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchAddResponse)
	err := c.cc.Invoke(ctx, DBFService_BatchAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBFServiceClient) BatchContains(ctx context.Context, in *BatchContainsRequest, opts ...grpc.CallOption) (*BatchContainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchContainsResponse)
	err := c.cc.Invoke(ctx, DBFService_BatchContains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBFServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, DBFService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBFServiceServer is the server API for DBFService service.
// All implementations must embed UnimplementedDBFServiceServer
// for forward compatibility.
//
// DBFService provides the gRPC API for the Distributed Bloom Filter.
type DBFServiceServer interface {
	// Add adds an item to the Bloom filter.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Remove removes an item from the Bloom filter.
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// Contains checks if an item exists in the Bloom filter.
	Contains(context.Context, *ContainsRequest) (*ContainsResponse, error)
	// BatchAdd adds multiple items to the Bloom filter.
	BatchAdd(context.Context, *BatchAddRequest) (*BatchAddResponse, error)
	// BatchContains checks if multiple items exist in the Bloom filter.
	BatchContains(context.Context, *BatchContainsRequest) (*BatchContainsResponse, error)
	// GetStats returns statistics about the Bloom filter and node.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedDBFServiceServer()
}

// UnimplementedDBFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBFServiceServer struct{}

func (UnimplementedDBFServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedDBFServiceServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedDBFServiceServer) Contains(context.Context, *ContainsRequest) (*ContainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contains not implemented")
}
func (UnimplementedDBFServiceServer) BatchAdd(context.Context, *BatchAddRequest) (*BatchAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAdd not implemented")
}
func (UnimplementedDBFServiceServer) BatchContains(context.Context, *BatchContainsRequest) (*BatchContainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchContains not implemented")
}
func (UnimplementedDBFServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedDBFServiceServer) mustEmbedUnimplementedDBFServiceServer() {}
func (UnimplementedDBFServiceServer) testEmbeddedByValue()                    {}

// UnsafeDBFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBFServiceServer will
// result in compilation errors.
type UnsafeDBFServiceServer interface {
	mustEmbedUnimplementedDBFServiceServer()
}

func RegisterDBFServiceServer(s grpc.ServiceRegistrar, srv DBFServiceServer) {
	// If the following call panics, it indicates UnimplementedDBFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBFService_ServiceDesc, srv)
}

func _DBFService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBFService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBFService_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).Contains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_Contains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).Contains(ctx, req.(*ContainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBFService_BatchAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).BatchAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_BatchAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).BatchAdd(ctx, req.(*BatchAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBFService_BatchContains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchContainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).BatchContains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_BatchContains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).BatchContains(ctx, req.(*BatchContainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBFService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBFServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBFService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBFServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBFService_ServiceDesc is the grpc.ServiceDesc for DBFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbf.DBFService",
	HandlerType: (*DBFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _DBFService_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DBFService_Remove_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _DBFService_Contains_Handler,
		},
		{
			MethodName: "BatchAdd",
			Handler:    _DBFService_BatchAdd_Handler,
		},
		{
			MethodName: "BatchContains",
			Handler:    _DBFService_BatchContains_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _DBFService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dbf.proto",
}
